// <auto-generated />
using System;
using Authetication.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authetication.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240531122431_initialTeste")]
    partial class initialTeste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Authetication.Server.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdmin")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("NomeAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordAdmin")
                        .HasColumnType("longtext");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Authetication.Server.Models.Coordenador", b =>
                {
                    b.Property<int>("IdCoordenador")
                        .HasColumnType("int");

                    b.Property<string>("EmailCoordenador")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("NomeCoordenador")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordCoordenador")
                        .HasColumnType("longtext");

                    b.HasKey("IdCoordenador");

                    b.ToTable("Coordenadores");
                });

            modelBuilder.Entity("Authetication.Server.Models.Fisioterapeuta", b =>
                {
                    b.Property<int>("IdFisio")
                        .HasColumnType("int");

                    b.Property<string>("EmailFisio")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("NomeFisio")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordFisio")
                        .HasColumnType("longtext");

                    b.Property<string>("SemestreFisio")
                        .HasColumnType("longtext");

                    b.HasKey("IdFisio");

                    b.ToTable("Fisioterapeutas");
                });

            modelBuilder.Entity("Authetication.Server.Models.Login", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("IdUser");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Authetication.Server.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiagnosticoClinico")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticoFisio")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailPaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("NomePaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCasa")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordPaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("Proficao")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Authetication.Server.Models.Admin", b =>
                {
                    b.HasOne("Authetication.Server.Models.Login", "Login")
                        .WithOne("Admin")
                        .HasForeignKey("Authetication.Server.Models.Admin", "IdAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Authetication.Server.Models.Coordenador", b =>
                {
                    b.HasOne("Authetication.Server.Models.Login", "Login")
                        .WithOne("Coordenador")
                        .HasForeignKey("Authetication.Server.Models.Coordenador", "IdCoordenador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Authetication.Server.Models.Fisioterapeuta", b =>
                {
                    b.HasOne("Authetication.Server.Models.Login", "Login")
                        .WithOne("Fisioterapeuta")
                        .HasForeignKey("Authetication.Server.Models.Fisioterapeuta", "IdFisio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Authetication.Server.Models.Paciente", b =>
                {
                    b.HasOne("Authetication.Server.Models.Login", "Login")
                        .WithOne("Paciente")
                        .HasForeignKey("Authetication.Server.Models.Paciente", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Authetication.Server.Models.Login", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Coordenador");

                    b.Navigation("Fisioterapeuta");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
